### ISSUE TITLE
Updated syntax for explicit sampling method

### ISSUE THREAD

**Issue by adieyal** [adieyal/dynamicprompts#11]
@akx I was wondering what your thoughts were about extending the syntax to support https://github.com/adieyal/sd-dynamic-prompts/issues/199. We need to address both wildcards and variants.  Here are some proposals, I'm not 100% behind any of them.

# Wildcards
https://github.com/adieyal/dynamicprompts/blob/0ffbfbdec91eb81d3e447169303de7ece81ae1cf/tests/prompts/parser/test_parser.py#L91-L109

# Variants
https://github.com/adieyal/dynamicprompts/blob/0ffbfbdec91eb81d3e447169303de7ece81ae1cf/tests/prompts/parser/test_parser.py#L114-L124

**Comment by akx** [comment]
Hmm... What about a consistent prefix, `?` for random and `!` (pronounced _bang!_) for combinatorial? Too terse?

| Feature | Random | Combinatorial |
| --- | --- | --- |
| Variant | `{?A\|B\|C}` | `{!A\|B\|C}` |
| Variant with range | `{?1-3$$A\|B\|C}` | `{!1-3$$A\|B\|C}` |
| Wildcard | `__?color__` | `__!color__` |

**Comment by adieyal** [comment]
`!` is actually quite relevant since it's reminiscent of the syntax used for combinations and permutations. Continuing with the sampler analogy, perhaps `~` might be better than `?` since it refers to probability distributions. I'm okay with the syntax being a little advanced, since it's an optional feature.
