### ISSUE TITLE
lexica.art API Too Many Requests

### ISSUE THREAD

**Issue by lingondricka2** [adieyal/dynamicprompts#119]
I can't find any documentation regarding the API

```
raise GeneratorException(f"Error while generating prompt: {e}") from e
dynamicprompts.generators.promptgenerator.GeneratorException: Error while generating prompt: 429 Client Error: 
Too Many Requests for url: https://lexica.art/api/v1/search?
q=cat%20in%20wizard%20outfit%20casting%20a%20spell,%20dramatic,%20magic%20effects,%20cute
```

Do I need to slightly alter the search words each time?

**Comment by lingondricka2** [comment]
I added some randomness to the search string each time and it seems to be working, is this a new API change, it worked fine 2 days ago?

**Comment by akx** [comment]
It's entirely possible it's a Lexica API change – we're not in control of the API, so we can't do much about this, sorry!
