### ISSUE TITLE
Rework ActionBuilder/Command/Generator hierarchy?

### ISSUE THREAD

**Issue by akx** [adieyal/dynamicprompts#13]
Right now it feels like the structure of these guys is a bit convoluted (sorry about a low-res screenshot, I couldn't coax PyCharm to build a full recursive diagram):

![image](https://user-images.githubusercontent.com/58669/215348588-caa6b095-e4a4-40f3-8758-8b807d41ee3d.png)

I feel it would be clearer if there weren't random and combinatorial subclasses of each command (or action, depending what you want to call them; the code isn't quite sure either 😂) but if the parser just always generated a tree of these as simple data classes (with a `SequenceCommand` always at the root, as things are now), and the generators (random, combinatorial, a combination thereof (#11)?) were responsible for walking the tree and yielding outputs.

If this sounds like it makes sense, I could start working on the refactor... WDYT @adieyal?

**Comment by adieyal** [comment]
In principle I think it's a good idea. 

With the combination of random and combinatorial, I was thinking that the parser would extract the sampling method if it was there (e.g. `:random` or `:combinatorial`) or simply set it to `default` if it isn't there. The generator would then decide what `default` actually meant, i.e. random for the `RandomPromptGenerator` and combinatorial for the `CombinatorialPromptGenerator`.

The benefit of delegating the generation to the Commands is that you could then more easily mix and match between random and combinatorial. If you think the generator-driven approach could handle it easily then go ahead. I'm looking forward to seeing it.

**Comment by akx** [comment]
Well, the issue with the current system is that we also have CombinatorialActionBuilder and RandomActionBuilder, so you'd have to pass both action builders to the parser, and it'd have to delegate... Anyway, I'll see what I can do refactor-wise! :)

**Comment by akx** [comment]
Done in #14 😁 🎉
