### ISSUE TITLE
Prompt with misplaced brace fails parsing

### ISSUE THREAD

**Issue by akx** [adieyal/dynamicprompts#22]
A prompt like

```
prompt with closing bra}ce but {parsed|accepted}
```

fails parsing:
```
pyparsing.exceptions.ParseException: Expected end of text, found '}'  (at char 23), (line:1, col:24)
```
We should probably parse that as a sequence of
* literal `prompt with closing bra}ce but `
* variant `parsed`, `accepted`

This is the upstream issue for https://github.com/adieyal/sd-dynamic-prompts/issues/212#issuecomment-1405465808

**Comment by Hexiota** [comment]
I ran into this with double underscore characters in my lora's filename, like so: `<lora:__negative:-1>`
